# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: file_series 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "file_series"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alex Dean"]
  s.date = "2016-05-13"
  s.description = "Automatically start writing to a new file every X seconds without any locking or file moving/renaming."
  s.email = "alex@crackpot.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "file_series.gemspec",
    "lib/file_series.rb",
    "script/jenkins.sh",
    "spec/file_series_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tedconf/file_series"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Write to a series of time-based files."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.99"])
      s.add_development_dependency(%q<ci_reporter_rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.6"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<timecop>, ["= 0.3.5"])
      s.add_development_dependency(%q<brakeman>, [">= 0"])
      s.add_development_dependency(%q<bundler-audit>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
      s.add_development_dependency(%q<rubocop-checkstyle_formatter>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.99"])
      s.add_dependency(%q<ci_reporter_rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.6"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<timecop>, ["= 0.3.5"])
      s.add_dependency(%q<brakeman>, [">= 0"])
      s.add_dependency(%q<bundler-audit>, [">= 0"])
      s.add_dependency(%q<rubocop>, [">= 0"])
      s.add_dependency(%q<rubocop-checkstyle_formatter>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.99"])
    s.add_dependency(%q<ci_reporter_rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.6"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<timecop>, ["= 0.3.5"])
    s.add_dependency(%q<brakeman>, [">= 0"])
    s.add_dependency(%q<bundler-audit>, [">= 0"])
    s.add_dependency(%q<rubocop>, [">= 0"])
    s.add_dependency(%q<rubocop-checkstyle_formatter>, [">= 0"])
  end
end

